name: vsf.linux cmake webassembly build

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  cmake-webassembly-build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true # without recursive

    - name: Checkout VSF Submodule
      run: git -C vsf submodule update --init

    - name: install depends
      run: |
          sudo apt-get update
          sudo apt-get install -y build-essential ninja-build libsdl2-dev libusb-dev libusb-1.0 python3 python3-pip
          pip3 install pytest pytest-bdd pexpect simple-hexdump
      shell: bash

    - name: install emsdk
      uses: mymindstorm/setup-emsdk@v11

    - name: Verify
      run: emcc -v

    - name: configure cmake
      run: cmake -GNinja -S ${SOURCE_PATH} -B ${SOURCE_PATH}/build
      env:
        VSF_PATH: ${{github.workspace}}/vsf
        SOURCE_PATH: ${{github.workspace}}/project/cmake/webassembly

    - name: build
      # Build your program with the given configuration
      run: cmake --build ${SOURCE_PATH}/build -v
      env:
        SOURCE_PATH: ${{github.workspace}}/project/cmake/webassembly

    - name: test
      run: pytest --verbose -o log_cli=true --log-cli-level="DEBUG" --vsf_template project/cmake/webassembly/build/vsf_template
      working-directory: ${{github.workspace}}/test/pytest
      env:
        VSF_PATH: ${{github.workspace}}/vsf
